# Generated by Django 4.2 on 2023-04-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree', models.CharField(max_length=255)),
                ('limit', models.IntegerField(default=20)),
            ],
        ),
    ]
